#!/usr/bin/env node
/**
 * Setup Script - Creates demo user and channel for testing
 * Run this before starting the NodeMCU simulator
 */

const fetch = require('node-fetch');

const SERVER_URL = process.env.SERVER_URL || 'http://192.168.1.12:3000';

// Demo user credentials
const DEMO_USER = {
  username: 'demo_user',
  email: 'demo@airquality.com',
  password: 'demo123'
};

// Demo channel details
const DEMO_CHANNEL = {
  name: 'Living Room Monitor',
  description: 'Air quality monitoring for living room with MQ-135 and DHT11 sensors'
};

async function setup() {
  console.log('╔════════════════════════════════════════════════════════════════╗');
  console.log('║         IoT Air Quality System - Setup Script                 ║');
  console.log('╚════════════════════════════════════════════════════════════════╝');
  console.log('');
  
  try {
    // Step 1: Register user
    console.log('👤 Creating demo user...');
    let userId;
    
    try {
      const registerResponse = await fetch(`${SERVER_URL}/api/auth/register`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(DEMO_USER)
      });
      
      if (registerResponse.ok) {
        const registerData = await registerResponse.json();
        userId = registerData.user.id;
        console.log('✅ User created successfully!');
        console.log(`   User ID: ${userId}`);
        console.log(`   Username: ${DEMO_USER.username}`);
        console.log(`   Email: ${DEMO_USER.email}`);
      } else {
        // User might already exist, try to login
        console.log('   User already exists, logging in...');
        const loginResponse = await fetch(`${SERVER_URL}/api/auth/login`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            email: DEMO_USER.email,
            password: DEMO_USER.password
          })
        });
        
        if (loginResponse.ok) {
          const loginData = await loginResponse.json();
          userId = loginData.user.id;
          console.log('✅ Logged in successfully!');
          console.log(`   User ID: ${userId}`);
        } else {
          throw new Error('Failed to login with existing user');
        }
      }
    } catch (error) {
      console.log('❌ Error with user creation/login:', error.message);
      throw error;
    }
    
    console.log('');
    
    // Step 2: Create channel
    console.log('📡 Creating demo channel...');
    const channelResponse = await fetch(`${SERVER_URL}/api/channels/create`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        userId,
        ...DEMO_CHANNEL
      })
    });
    
    if (!channelResponse.ok) {
      throw new Error('Failed to create channel');
    }
    
    const channelData = await channelResponse.json();
    const channel = channelData.channel;
    
    console.log('✅ Channel created successfully!');
    console.log(`   Channel ID: ${channel.id}`);
    console.log(`   Name: ${channel.name}`);
    console.log(`   Read API Key: ${channel.readApiKey}`);
    console.log(`   Write API Key: ${channel.writeApiKey}`);
    console.log('');
    
    // Step 3: Display setup instructions
    console.log('╔════════════════════════════════════════════════════════════════╗');
    console.log('║                    SETUP COMPLETE!                             ║');
    console.log('╚════════════════════════════════════════════════════════════════╝');
    console.log('');
    console.log('🚀 Next Steps:');
    console.log('');
    console.log('1️⃣  Start the NodeMCU simulator:');
    console.log('');
    console.log(`   CHANNEL_ID=${channel.id} WRITE_API_KEY=${channel.writeApiKey} node simulator/nodemcu.js`);
    console.log('');
    console.log('2️⃣  Login to mobile app with:');
    console.log(`   Email: ${DEMO_USER.email}`);
    console.log(`   Password: ${DEMO_USER.password}`);
    console.log('');
    console.log('3️⃣  Select channel: "${channel.name}"');
    console.log('');
    console.log('💾 Credentials saved to: .env.simulator');
    console.log('');
    
    // Save to .env file
    const fs = require('fs');
    const envContent = `# NodeMCU Simulator Configuration
# Generated by setup script

SERVER_URL=${SERVER_URL}
CHANNEL_ID=${channel.id}
WRITE_API_KEY=${channel.writeApiKey}

# Demo User Credentials (for mobile app)
DEMO_EMAIL=${DEMO_USER.email}
DEMO_PASSWORD=${DEMO_USER.password}
DEMO_USER_ID=${userId}

# Channel Info
CHANNEL_NAME=${channel.name}
READ_API_KEY=${channel.readApiKey}
`;
    
    fs.writeFileSync('.env.simulator', envContent);
    
    console.log('✅ Setup complete! You can now start the simulator and mobile app.');
    
  } catch (error) {
    console.error('');
    console.error('❌ Setup failed:', error.message);
    console.error('');
    console.error('Please ensure:');
    console.error('  1. Backend server is running (npm run start:api)');
    console.error(`  2. Server is accessible at ${SERVER_URL}`);
    process.exit(1);
  }
}

// Run setup
setup();
